"""
utils/doc_generator.py
─────────────────────────────────────────────────────────────────
Automated Technical Documentation Generator.
Analyzes the FastAPI application, tools, and Quality Gate configuration
to generate a comprehensive markdown documentation file.
─────────────────────────────────────────────────────────────────
"""

import os
import sys
from pathlib import Path

# Adjust path to import backend modules
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from fastapi.routing import APIRoute
from main import app
from utils.quality_gate import QualityGate
import tools


def generate_docs() -> str:
    """
    Introspects the FastAPI application, tools, and quality gates
    to generate technical documentation in markdown format.
    """
    doc_lines = [
        "# Automated Technical Documentation",
        "",
        "> This document is automatically generated by the documentation pipeline.",
        "",
        "## 1. FastAPI Router & Endpoints",
        "",
        "| Endpoint Path | HTTP Method | Summary | Request Schema | Response Schema |",
        "|---|---|---|---|---|",
    ]

    # ── Introspect Router ─────────────────────────────────────────────────────
    for route in app.routes:
        if isinstance(route, APIRoute):
            methods = ", ".join(route.methods)
            summary = route.summary or route.description or "No description"
            # Format clean multiline text to single line for markdown table
            summary = summary.replace("\n", " ").strip()
            
            req_model = route.body_field.field_info.annotation.__name__ if (route.body_field and hasattr(route.body_field, 'field_info') and hasattr(route.body_field.field_info, 'annotation')) else "None"
            resp_model = route.response_model.__name__ if route.response_model else "Dynamic"
            
            doc_lines.append(
                f"| `{route.path}` | `{methods}` | {summary} | `{req_model}` | `{resp_model}` |"
            )

    # ── Introspect Custom Tools ───────────────────────────────────────────────
    doc_lines.extend([
        "",
        "## 2. Integrated Utility & Agent Tools",
        "",
        "These tools are used for content research, formatting, and validation checks:",
        "",
    ])

    tool_classes = [
        ("TavilySearchTool", tools.TavilySearchTool),
        ("GrammarCheckTool", tools.GrammarCheckTool),
        ("CrewAIGrammarCheckTool", tools.CrewAIGrammarCheckTool),
        ("SEOKeywordAnalyzer", tools.SEOKeywordAnalyzer),
        ("CrewAISEOTool", tools.CrewAISEOTool),
        ("PlagiarismDetector", tools.PlagiarismDetector),
        ("CrewAIPlagiarismTool", tools.CrewAIPlagiarismTool),
    ]

    for name, cls in tool_classes:
        doc = cls.__doc__ or "No documentation available."
        doc_lines.append(f"### `{name}`")
        doc_lines.append("")
        doc_lines.append(f"**Class Path:** `tools.{cls.__name__}`")
        doc_lines.append("")
        doc_lines.append("**Description:**")
        # Clean formatting indentation
        doc_lines.append(doc.strip())
        doc_lines.append("")

    # ── Quality Gate Parameters ────────────────────────────────────────────────
    gate = QualityGate()
    doc_lines.extend([
        "## 3. Automated Quality Gate System",
        "",
        "The Quality Gate enforces strict content criteria before returning articles to the client:",
        "",
        f"- **Grammar Threshold:** Maximum of `{gate.max_grammar_errors}` errors allowed.",
        f"- **SEO Score Threshold:** Minimum of `{gate.min_seo_score}/100` score required.",
        f"- **Plagiarism Threshold:** Maximum of `{gate.max_plagiarism_pct}%` duplicate content allowed.",
        "",
        "### Score Weightings",
        "",
        "Quality score computation is dynamically weighted based on check inputs:",
        "",
        "| Evaluation State | Grammar Weight | SEO Weight | Plagiarism Weight |",
        "|---|---|---|---|",
        "| **With Reference Docs** (Full Plagiarism Check) | 30% | 40% | 30% |",
        "| **Without Reference Docs** (Plagiarism Check Skipped) | 40% | 60% | 0% |",
        "",
    ])

    # ── Write file ────────────────────────────────────────────────────────────
    output_content = "\n".join(doc_lines)
    
    docs_dir = Path(__file__).parent.parent.parent / "docs"
    docs_dir.mkdir(exist_ok=True)
    
    output_path = docs_dir / "architecture_and_api.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(output_content)

    print(f"Documentation generated successfully at: {output_path.resolve()}")
    return output_content


if __name__ == "__main__":
    generate_docs()
